name: flutter_ios_liquidglass_example
description: Example app for the Flutter iOS Liquid Glass package
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1
  flutter: ">=3.16.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_ios_liquidglass:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
